stages:
  - test
  - build

build:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit-test:
  image: node:latest
  stage: test
  script:
    - npm install
    - npm run test:unit

lint-test:
  image: node:latest
  stage: test
  script:
    - npm install
    - npm run lint
