stages:
  - test
  - build

unit-test:
  image: node:latest
  stage: test
  script:
    - npm install
    - npm run test:unit
  coverage: '/All files\s+\|\s+\d+\.\d+/'
  artifacts:
    reports:
      junit:
        - test-results.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

lint-test:
  image: node:latest
  stage: test
  script:
    - npm install
    - npm run lint

build:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
