stages:
  - test
  - build
  - publish

unit-test:
  image: node:latest
  stage: test
  script:
    - npm install
    - npm run test:unit
  coverage: '/All files\s+\|\s+\d+\.\d+/'
  artifacts:
    reports:
      junit:
        - test-results.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

lint-test:
  image: node:latest
  stage: test
  script:
    - npm install
    - npm run lint

build:
  image: node:latest
  stage: build
  script:
    - apt install python3
    - npm install
    - ./version_build.sh
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
      - public/conf/build

publish:
  image: node:latest
  stage: publish
  needs: [build]
  script:
    - BASE_URL=`echo $CI_REPOSITORY_URL | sed "s;\/*$CI_PROJECT_PATH.*;;"`
    - REPO_URL="$BASE_URL/lucterios2/lucterios.git"
    - REPO_DIR=lucterios
    - rm -fr $REPO_DIR
    - git clone $REPO_URL $REPO_DIR
    - cp public/conf/build $REPO_DIR/client/build_client
    - cd $REPO_DIR
    - git status